# Remove adguard from history.
# When the file is named "adguard.yaml", the file editor is not able to open it.
history:
  exclude:
    entities:
      - sensor.adguard_average_processing_speed
      - sensor.adguard_dns_queries
      - sensor.adguard_dns_queries_blocked_ratio
      - sensor.adguard_parental_control_blocked
      - sensor.adguard_safe_browsing_blocked
      - sensor.adguard_safe_searches_enforced
      - switch.adguard_filtering
      - switch.adguard_parental_control
      - switch.adguard_protection
      - switch.adguard_safe_browsing
      - switch.adguard_safe_search
