logbook:
  exclude:
    entities:
      - device_tracker.christian_iphone
      - device_tracker.anita_iphone
      - device_tracker.elias_iphone
      - device_tracker.elias_ipad
      - device_tracker.anna_mavie_iphone
      - device_tracker.jessica_iphone
      - device_tracker.jessicas_macbook_air
