logbook:
  exclude:
    entities:
      - device_tracker.eliass_iphone
      - sensor.eliass_iphone_activity
      - sensor.eliass_iphone_average_active_pace
      - sensor.eliass_iphone_battery_level
      - sensor.eliass_iphone_battery_state
      - sensor.eliass_iphone_bssid
      - sensor.eliass_iphone_connection_type
      - sensor.eliass_iphone_distance
      - sensor.eliass_iphone_floors_ascended
      - sensor.eliass_iphone_floors_descended
      - sensor.eliass_iphone_geocoded_location
      - sensor.eliass_iphone_last_update_trigger
      - sensor.eliass_iphone_sim_1
      - sensor.eliass_iphone_ssid
      - sensor.eliass_iphone_steps
      - sensor.eliass_iphone_storage

history:
  exclude:
    entities:
      - device_tracker.elias
      - device_tracker.eliass_iphone
      - sensor.eliass_iphone_activity
      - sensor.eliass_iphone_average_active_pace
      - sensor.eliass_iphone_battery_level
      - sensor.eliass_iphone_battery_state
      - sensor.eliass_iphone_bssid
      - sensor.eliass_iphone_connection_type
      - sensor.eliass_iphone_distance
      - sensor.eliass_iphone_floors_ascended
      - sensor.eliass_iphone_floors_descended
      - sensor.eliass_iphone_geocoded_location
      - sensor.eliass_iphone_last_update_trigger
      - sensor.eliass_iphone_sim_1
      - sensor.eliass_iphone_ssid
      - sensor.eliass_iphone_steps
      - sensor.eliass_iphone_storage
