logbook:
  exclude:
    entities:
      - binary_sensor.fritz_box_4040_connectivity
      - sensor.fritz_box_4040_connection_uptime
      - sensor.fritz_box_4040_device_uptime
      - sensor.fritz_box_4040_gb_received
      - sensor.fritz_box_4040_gb_sent
      - sensor.fritz_box_4040_kb_s_received
      - sensor.fritz_box_4040_kb_s_sent
      - sensor.fritz_box_4040_max_kbit_s_received
      - sensor.fritz_box_4040_max_kbit_s_sent
      - switch.fritz_box_4040_wi_fi_fritz_box_gastzugang
      - switch.fritz_box_4040_wi_fi_openwrt
      - switch.fritz_box_4040_wi_fi_openwrt_5ghz

history:
  exclude:
    entities:
      - binary_sensor.fritz_box_4040_connectivity
      - sensor.fritz_box_4040_connection_uptime
      - sensor.fritz_box_4040_device_uptime
      - sensor.fritz_box_4040_gb_received
      - sensor.fritz_box_4040_gb_sent
      - sensor.fritz_box_4040_kb_s_received
      - sensor.fritz_box_4040_kb_s_sent
      - sensor.fritz_box_4040_max_kbit_s_received
      - sensor.fritz_box_4040_max_kbit_s_sent
      - switch.fritz_box_4040_wi_fi_fritz_box_gastzugang
      - switch.fritz_box_4040_wi_fi_openwrt
      - switch.fritz_box_4040_wi_fi_openwrt_5ghz
