frontend:
  themes: !include_dir_merge_named ../themes

lovelace:
  mode: yaml
  resources:
    - type: module
      url: /hacsfiles/lovelace-time-picker-card/time-picker-card.js
    - type: module
      url: /hacsfiles/fan-percent-button-row/fan-percent-button-row.js
    - type: module
      url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
    - type: module
      url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    - type: module
      url: /hacsfiles/lovelace-horizon-card/lovelace-horizon-card.js
