frontend:
  themes: !include_dir_merge_named ../themes

lovelace:
  mode: yaml
  resources:
    - type: module
      url: /hacsfiles/lovelace-time-picker-card/time-picker-card.js
    - type: module
      url: /hacsfiles/fan-control-entity-row/fan-control-entity-row.js
    - type: module
      url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js
