# For new devices see https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md
# On my MAC run tuya-cli wizard. You will have to use any device_id.
# Provide a static IP address.  Modify device in app, choose "Information des Geräts", look at Mac address and search this address in your router.

localtuya:
  - host: 10.0.0.206
    device_id: !secret tuya_plug_04_device_id
    local_key: !secret tuya_plug_04_local_key
    friendly_name: plug_04
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: plug_04
        id: 1
  - host: 10.0.0.207
    device_id: !secret tuya_plug_05_device_id
    local_key: !secret tuya_plug_05_local_key
    friendly_name: plug_05
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: plug_05
        id: 1
  - host: 10.0.0.208
    device_id: !secret tuya_plug_06_device_id
    local_key: !secret tuya_plug_06_local_key
    friendly_name: plug_06
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: plug_06
        id: 1
  - host: 10.0.0.209
    device_id: !secret tuya_plug_07_device_id
    local_key: !secret tuya_plug_07_local_key
    friendly_name: plug_07
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: plug_07
        id: 1
  - host: 10.0.0.210
    device_id: !secret tuya_plug_08_device_id
    local_key: !secret tuya_plug_08_local_key
    friendly_name: plug_08
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: plug_08
        id: 1
  - host: 10.0.0.221
    device_id: !secret tuya_plug_09_device_id
    local_key: !secret tuya_plug_09_local_key
    friendly_name: plug_09
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: plug_09
        id: 1
  - host: 10.0.0.222
    device_id: !secret tuya_plug_10_device_id
    local_key: !secret tuya_plug_10_local_key
    friendly_name: plug_10
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: plug_10
        id: 1
  - host: 10.0.0.223
    device_id: !secret tuya_plug_11_device_id
    local_key: !secret tuya_plug_11_local_key
    friendly_name: plug_11
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: plug_11
        id: 1
  - host: 10.0.0.224
    device_id: !secret tuya_plug_12_device_id
    local_key: !secret tuya_plug_12_local_key
    friendly_name: plug_12
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: plug_12
        id: 1
  - host: 10.0.0.225
    device_id: !secret tuya_plug_13_device_id
    local_key: !secret tuya_plug_13_local_key
    friendly_name: plug_13
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: plug_13
        id: 1
