# Connecting Siemens Logo via modbus
# Port 502 ist der Standard für Modbus-TCP
#
# How to enable modbus on Sienems Logo
# - Tools -> Ethernet Connections…
# - Enter IP address of your LOGO…
# - Right click on Etnernet Connections -> Add server connection -> Modbus Connection
# - Upload your program to LOGO
#
# Coil = VB-address * 8 + bit (V100.0 = 8 * 100 + 0 = 800)
# Register = VW-address / 2 (VW124 / 2 = register 62)
# See https://community.home-assistant.io/t/siemens-logo-8/129281/18

modbus:
  name: hub1
  type: tcp
  host: 10.0.0.211
  port: 502
  sensors:
    - name: modbus_sensor_01
      address: 58
      scan_interval: 10
    - name: modbus_sensor_02
      address: 59
      scan_interval: 10
    - name: modbus_sensor_03
      address: 60
      scan_interval: 10
    - name: modbus_sensor_04
      address: 61
      scan_interval: 10
    - name: modbus_sensor_05
      address: 62
      scan_interval: 10
    - name: modbus_sensor_06
      address: 63
      scan_interval: 10

# Modbus switches, do not use directly as they have to be pulsed
  switches:
    - name: modbus_switch_01
      address: 800
      input_type: coil
    - name: modbus_switch_02
      address: 801
      input_type: coil
    - name: modbus_switch_03
      address: 802
      input_type: coil
    - name: modbus_switch_04
      address: 803
      input_type: coil
    - name: modbus_switch_05
      address: 804
      input_type: coil
    - name: modbus_switch_06
      address: 805
      input_type: coil
    - name: modbus_switch_07
      address: 806
      input_type: coil
    - name: modbus_switch_08
      address: 807
      input_type: coil
    - name: modbus_switch_09
      address: 808
      input_type: coil
    - name: modbus_switch_10
      address: 809
      input_type: coil
    - name: modbus_switch_11
      address: 810
      input_type: coil
    - name: modbus_switch_12
      address: 811
      input_type: coil
    - name: modbus_switch_13
      address: 812
      input_type: coil
    - name: modbus_switch_14
      address: 814
      input_type: coil

# Template switches for direct use (250ms pulse)
switch:
  - platform: template
    switches:

      blind_livingroom_window_up:
        friendly_name: "Blind living room window up"
        value_template: "{{ is_state('switch.modbus_switch_01', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_01
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_01
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_01
        icon_template: "mdi:blinds"
      blind_livingroom_window_down:
        friendly_name: "Blind living room window down"
        value_template: "{{ is_state('switch.modbus_switch_02', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_02
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_02
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_02
        icon_template: "mdi:blinds"
        
      blind_livingroom_door_up:
        friendly_name: "Blind living room door up"
        value_template: "{{ is_state('switch.modbus_switch_03', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_03
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_03
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_03
        icon_template: "mdi:blinds"
      blind_livingroom_door_down:
        friendly_name: "Blind living room door down"
        value_template: "{{ is_state('switch.modbus_switch_04', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_04
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_04
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_04
        icon_template: "mdi:blinds"
        
      blind_kitchen_door_up:
        friendly_name: "Blind kitchen door up"
        value_template: "{{ is_state('switch.modbus_switch_05', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_05
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_05
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_05
        icon_template: "mdi:blinds"
      blind_kitchen_door_down:
        friendly_name: "Blind kitchen door down"
        value_template: "{{ is_state('switch.modbus_switch_06', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_06
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_06
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_06
        icon_template: "mdi:blinds"

      blind_kitchen_left_up:
        friendly_name: "Blind kitchen left up"
        value_template: "{{ is_state('switch.modbus_switch_07', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_07
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_07
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_07
        icon_template: "mdi:blinds"
      blind_kitchen_left_down:
        friendly_name: "Blind kitchen left down"
        value_template: "{{ is_state('switch.modbus_switch_08', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_08
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_08
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_08
        icon_template: "mdi:blinds"

      blind_kitchen_right_up:
        friendly_name: "Blind kitchen right up"
        value_template: "{{ is_state('switch.modbus_switch_09', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_09
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_09
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_09
        icon_template: "mdi:blinds"
      blind_kitchen_right_down:
        friendly_name: "Blind kitchen right down"
        value_template: "{{ is_state('switch.modbus_switch_10', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_10
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_10
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_10
        icon_template: "mdi:blinds"

      blind_bedroom_up:
        friendly_name: "Blind bedroom up"
        value_template: "{{ is_state('switch.modbus_switch_11', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_11
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_11
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_11
        icon_template: "mdi:blinds"
      blind_bedroom_down:
        friendly_name: "Blind bedroom down"
        value_template: "{{ is_state('switch.modbus_switch_12', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_12
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_12
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_12
        icon_template: "mdi:blinds"

      blind_all_up:
        friendly_name: "All blinds up"
        value_template: "{{ is_state('switch.modbus_switch_13', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_13
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_13
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_13
        icon_template: "mdi:blinds"
      blind_all_down:
        friendly_name: "All Blinds down"
        value_template: "{{ is_state('switch.modbus_switch_14', 'on') }}"
        turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.modbus_switch_14
        - delay:
            milliseconds: 250
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_14
        turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.modbus_switch_14
        icon_template: "mdi:blinds"

logbook:
  exclude:
    entities:
      - sensor.modbus_sensor_01
      - sensor.modbus_sensor_02
      - sensor.modbus_sensor_03
      - sensor.modbus_sensor_04
      - sensor.modbus_sensor_05
      - sensor.modbus_sensor_06
      - switch.modbus_switch_01
      - switch.modbus_switch_02
      - switch.modbus_switch_03
      - switch.modbus_switch_04
      - switch.modbus_switch_05
      - switch.modbus_switch_06
      - switch.modbus_switch_07
      - switch.modbus_switch_08
      - switch.modbus_switch_09
      - switch.modbus_switch_10
      - switch.modbus_switch_11
      - switch.modbus_switch_12
      - switch.modbus_switch_13
      - switch.modbus_switch_14

history:
  exclude:
    entities:
      - sensor.modbus_sensor_01
      - sensor.modbus_sensor_02
      - sensor.modbus_sensor_03
      - sensor.modbus_sensor_04
      - sensor.modbus_sensor_05
      - sensor.modbus_sensor_06
      - switch.modbus_switch_01
      - switch.modbus_switch_02
      - switch.modbus_switch_03
      - switch.modbus_switch_04
      - switch.modbus_switch_05
      - switch.modbus_switch_06
      - switch.modbus_switch_07
      - switch.modbus_switch_08
      - switch.modbus_switch_09
      - switch.modbus_switch_10
      - switch.modbus_switch_11
      - switch.modbus_switch_12
      - switch.modbus_switch_13
      - switch.modbus_switch_14
      - switch.blind_livingroom_window_up
      - switch.blind_livingroom_window_down
      - switch.blind_livingroom_door_up
      - switch.blind_livingroom_door_down
      - switch.blind_kitchen_door_up
      - switch.blind_kitchen_door_down
      - switch.blind_kitchen_left_up
      - switch.blind_kitchen_left_down
      - switch.blind_kitchen_right_up
      - switch.blind_kitchen_right_down
      - switch.blind_bedroom_up
      - switch.blind_bedroom_down
      - switch.blind_all_up
      - switch.blind_all_down
