# HTTP access
http:
#  ssl_certificate: !secret ssl_certificate
#  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 2
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
