telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_token
    parse_mode: html
    allowed_chat_ids:
      - !secret telegram_chat_id_1
      - !secret telegram_chat_id_2

notify:
  - name: telegram_all
    platform: telegram
    chat_id: !secret telegram_chat_id_1
  - name: telegram_admin
    platform: telegram
    chat_id: !secret telegram_chat_id_2
    
logbook:
  exclude:
    entities:
      - persistent_notification.config_entry_discovery
      - persistent_notification.http_login

history:
  exclude:
    entities:
      - persistent_notification.config_entry_discovery
      - persistent_notification.http_login
