input_boolean:
  poolmodus:
    name: Gibt an, ob der Poolmodus aktiv ist
    icon: mdi:pool

# Dadurch, dass ich Netzwerk im Poolraum gebraucht habe, habe ich eine zweipolige Stromleitung zur Übertragung des Netzwerkes über Fritz! Powerline benutzt.
# Diese Leitung war früher für die Übertragung der Pool-Heizung zuständig, diese Funktion habe ich damit verloren.
# Den Ersatz der Leitung habe ich wie folgt durchgeführt:
# - Im Pool-Technikraum gibt es den switch.power_01, der am Strom hängt, wenn geheizt werden soll
# - Dann registriert er sich über WLAN beim HomeAssistant
# - Die folgende Automatisierung läuft an und schaltet ein Relay im Heizungskeller
# - Das Relai führt die ursprüngliche Aktion der Heizungs-Leitung durch.
automation:
- id: 'pool_heater_on'
  alias: 'Service: Pool heater on'
  trigger:
  - platform: state
    entity_id: switch.power_01
    from: "unavailable"
  condition:
  - condition: state
    entity_id: input_boolean.poolmodus
    state: 'on'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.ventilation_relay_4
  mode: single

- id: 'pool_heater_off'
  alias: 'Service: Pool heater off'
  trigger:
  - platform: state
    entity_id: switch.power_01
    to: "unavailable"
  condition:
  - condition: state
    entity_id: input_boolean.poolmodus
    state: 'on'
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.ventilation_relay_4
  mode: single

# Warnt, falls der Poolmodus ausserhalb der Saison (15.10. - 15.04.) aktiviert wird
- id: 'pool_mode_off_season_alarm'
  alias: 'Service: Alarm when poolmodus is activated outside the season'
  trigger:
  - platform: state
    entity_id: input_boolean.poolmodus
    to: 'on'
  condition:
  - condition: template
    value_template: >-
      {% set today = now().strftime('%m%d') | int %}
      {{ today >= 1015 or today <= 415 }}
  action:
  - action: notify.send_message
    data:
      entity_id: notify.telegram_admin
      message: "Meister, der Poolmodus wurde ausserhalb der Saison (15.10. - 15.04.) aktiviert!"
  mode: single
