automation:
- id: 'turn_off_toaster'
  alias: 'Service: Turn off toaster after 20 minutes'
  mode: restart
  trigger:
    platform: state
    entity_id: switch.plug_17
    to: 'on'
  action:
    - delay:
        minutes: 20
    - if:
        - alias: "If toaster is still running"
          condition: state
          entity_id: switch.plug_17
          state: 'on'
      then:
        - service: switch.turn_off
          entity_id: switch.plug_17
        - action: notify.send_message
          data:
            entity_id: notify.telegram_all
            message: "Toaster wurde nach 20 Minuten automatisch ausgeschalten. *Aufpassen!*"
