switch:
  - platform: wake_on_lan
    host: arbeitszimmer.lan
    mac: !secret arbeitszimmer_mac
    name: "Arbeitszimmer"
  - platform: wake_on_lan
    host: diskstation.lan
    mac: !secret diskstation_mac
    name: "Diskstation"
