#
# Weihnachtsbeleuchtung
#

# Die Stecker hier zuordnen
group:
  weihnachtsbeleuchtung_wohnzimmer:
    name: "Weihnachtsbeleuchtung Wohnzimmer"
    entities:
      - switch.plug_03
      - switch.shellyplusplugs_e465b84329a8_switch_0

  weihnachtsbeleuchtung_rest:
    name: "Weihnachtsbeleuchtung Rest"
    entities:
      - switch.shellyplusplugs_e86beae2f644_switch_0
      - switch.plug_04
      - switch.plug_05
      - switch.plug_06
      - switch.plug_07
      - switch.plug_09
      - switch.plug_10
      - switch.plug_11
      - switch.plug_12
      - switch.plug_13
      - switch.shellyplusplugs_d48afc7ae358_switch_0
      - switch.plug_15_switch_0

input_boolean:
  weihnachtsmodus:
    name: Gibt an, ob der Weihnachtsmodus aktiv ist
    icon: mdi:pine-tree

automation:
- id: 'turn_on_xmas_lights'
  alias: 'Service: Turn on x-mas lights'
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: state
    entity_id: input_boolean.weihnachtsmodus
    state: 'on'
  action:
    action: switch.turn_on
    target:
      entity_id:
        - group.weihnachtsbeleuchtung_wohnzimmer
        - group.weihnachtsbeleuchtung_rest

- id: 'turn_off_xmas_lights'
  alias: 'Service: Turn off x-mas lights'
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.weihnachtsmodus
    state: 'on'
  action:
    - action: cover.close_cover
      target:
        entity_id:
          - cover.bedroom_window
          - cover.livingroom_window
    - delay: '00:00:15'
    - action: switch.turn_off
      target:
        entity_id: group.weihnachtsbeleuchtung_rest

- id: 'turn_off_xmas_lights_living_room'
  alias: 'Service: Turn off x-mas lights in the living room'
  trigger:
  - platform: time
    at: '00:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.weihnachtsmodus
    state: 'on'
  action:
    - action: switch.turn_off
      target:
        entity_id: group.weihnachtsbeleuchtung_wohnzimmer
