language: python
python:
  - "3.7"
before_install:
  - mv config/travis_secrets.yaml config/secrets.yaml
  - sudo apt-get install -y libudev-dev
install:
  - pip3 install homeassistant
  - pip3 install websocket
  - pip3 install bs4
script:
  - hass -c config --script check_config
