- id: '1584961424173'
  alias: 'Service: make full backup'
  description: Erstellt jeden Sonntag ein volles Backup
  trigger:
  - at: 03:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - data_template:
      name: Backup {{ now().strftime('%Y-%m-%d') }}
    service: hassio.snapshot_full
