# Configure a default set of integrations for Home Assistant to load
# see https://www.home-assistant.io/integrations/default_config/
default_config:

# Enable configuration through packages
homeassistant:
  packages: !include_dir_named packages/

# Include standard files
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
