# Dummy secrets.yaml for Github test workflow

# https
base_url: https://hass.io:8123
external_url: https://hass.io:8123
internal_url: https://hassio:8123

# WLAN
wlan_ssid: xxx
wlan_password: xxxxxxxx
captive_password: xxxxxxxx

# Passwords
vusolo4k_password: xxxxxxxx

# MAC addresses
arbeitszimmer_mac: 00:00:00:00:00:00
sasmsung_mac: 00:00:00:00:00:00
vuplus_mac: 00:00:00:00:00:00
diskstation_mac: 00:00:00:00:00:00

# Husqvarna Automower
husqvarna_username: user@host.com
husqvarna_password: xxxxxxxx
husqvarna_maps_url: https://test.com

# Google API key
google_api_key: xxxxxxxx

# Telegram Token
telegram_token: xxxxxxxx:xxxxxxxx
telegram_chat_id_1: -000000000
telegram_chat_id_2: -000000000

# Waste data
bmv_ort: Ort
bmv_strasse: Strasse
bmv_hausnummer: 1

# Samsung TV
api_key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
device_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

# LocalTuya
tuya_plug_04_device_id: xxxxxxxxxxxxxxxxxxxxxx
tuya_plug_04_local_key: xxxxxxxxxxxxxxxx
tuya_plug_05_device_id: xxxxxxxxxxxxxxxxxxxxxx
tuya_plug_05_local_key: xxxxxxxxxxxxxxxx
tuya_plug_06_device_id: xxxxxxxxxxxxxxxxxxxxxx
tuya_plug_06_local_key: xxxxxxxxxxxxxxxx
tuya_plug_07_device_id: xxxxxxxxxxxxxxxxxxxxxx
tuya_plug_07_local_key: xxxxxxxxxxxxxxxx
tuya_plug_08_device_id: xxxxxxxxxxxxxxxxxxxxxx
tuya_plug_08_local_key: xxxxxxxxxxxxxxxx
tuya_plug_09_device_id: xxxxxxxxxxxxxxxxxxxxxx
tuya_plug_09_local_key: xxxxxxxxxxxxxxxx
tuya_plug_10_device_id: xxxxxxxxxxxxxxxxxxxxxx
tuya_plug_10_local_key: xxxxxxxxxxxxxxxx
tuya_plug_11_device_id: xxxxxxxxxxxxxxxxxxxxxx
tuya_plug_11_local_key: xxxxxxxxxxxxxxxx
tuya_plug_12_device_id: xxxxxxxxxxxxxxxxxxxxxx
tuya_plug_12_local_key: xxxxxxxxxxxxxxxx
tuya_plug_13_device_id: xxxxxxxxxxxxxxxxxxxxxx
tuya_plug_13_local_key: xxxxxxxxxxxxxxxx

# Roborock S7
xiaomi_vacuum_host: 127.0.0.1
xiaomi_vacuum_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xiaomi_cloud_username: user@host.com
xiaomi_cloud_password: xxxxxxxx
