# Dummy secrets.yaml for Travis

# https
base_url: https://hass.io:8123
external_url: https://hass.io:8123
internal_url: https://hassio:8123
#ssl_certificate: fullchain.pem
#ssl_key: privkey.pem

# Devices
fritzbox_password: xxxxxxxx

# WLAN
wlan_ssid: xxx
wlan_password: xxxxxxxx
captive_password: xxxxxxxx

# Passwords
vusolo4k_password: xxxxxxxx

# MAC addresses
arbeitszimmer_mac: 00:00:00:00:00:00
sasmsung_mac: 00:00:00:00:00:00
vuplus_mac: 00:00:00:00:00:00
diskstation_mac: 00:00:00:00:00:00

# Husqvarna Automower
husqvarna_username: user@host.com
husqvarna_password: xxxxxxxx
husqvarna_maps_url: https://test.com

# Google API key
google_api_key: xxxxxxxx

# Telegram Token
telegram_token: xxxxxxxx:xxxxxxxx
telegram_chat_id: -000000000

# Waste data
bmv_ort: Ort
bmv_strasse: Strasse
bmv_hausnummer: 1

# Samsung TV
api_key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
device_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

# Google
google_client_id: 111111111111-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
google_client_secret: xxxxxxxxxxxxxxxxxxxxxxxx

# Tuya devices
tuya_username: a@b.com
tuya_password: XXXXXXX
tuya_countrycode: 01