wifi:
  # Which WLAN
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .lan
  
  # Static IP
  manual_ip:
    static_ip: ${ip_adress}
    gateway: 10.0.0.138
    subnet: 255.255.255.0
    dns1: 10.0.0.100
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${short_name} AP"
    password: !secret captive_password

# Start a WiFi hotspot on WiFi connection errors
captive_portal:

# Enable Home Assistant API
api:

# Enable Over The Air update (OTA)
ota:

# Enable web server
web_server:
  port: 80

sensor:
# report WLAN strength
  - platform: wifi_signal
    name: ${short_name} Signal
    update_interval: 60s
# Reports how long the device has been powered (in minutes)
  - platform: uptime
    name: ${short_name} Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes

text_sensor:
# Reports the ESPHome Version with compile date
  - platform: version
    name: ${short_name} ESPHome Version

switch:
# Allow rebooting per switch
  - platform: restart
    name: "${short_name} Restart"
