# Sonoff 4CH Pro R2
# Link to device: https://de.aliexpress.com/item/33059063659.html
# How to install: https://reid-projects.com/how-to-install-esphome-on-sonoff-4ch-pro-r2/
# Config: https://esphome-configs.io/devices/sonoff-4ch-pro-r2/

substitutions:
  device_name: switch-ventilation
  device_description: Schalter Kontrollierte Wohnraumlüftung
  friendly_name: Switch ventilation
  short_name: ventilation
  ip_adress: 10.0.0.205

esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP8266
  board: esp01_1m

# Network settings
packages:
  wifi: !include .network.yaml

binary_sensor:
  - platform: gpio
    on_press:
      then:
        - switch.toggle: relay1
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${short_name} Button 1"
    internal: true
  - platform: gpio
    on_press:
      then:
        - switch.toggle: relay2
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "${short_name} Button 2"
    internal: true
  - platform: gpio
    on_press:
      then:
        - switch.toggle: relay3
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "${short_name} Button 3"
    internal: true
  - platform: gpio
    on_press:
      then:
        - switch.toggle: relay4
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "${short_name} Button 4"
    internal: true

switch:
  - platform: gpio
    id: relay1
    name: "${short_name} Relay 1"
    pin: GPIO12
    icon: mdi:electric-switch
    interlock: &interlock_group [relay1, relay2, relay3]
  - platform: gpio
    id: relay2
    name: "${short_name} Relay 2"
    pin: GPIO5
    icon: mdi:electric-switch
    interlock: *interlock_group
  - platform: gpio
    id: relay3
    name: "${short_name} Relay 3"
    pin: GPIO4
    icon: mdi:electric-switch
    interlock: *interlock_group
  - platform: gpio
    id: relay4
    name: "${short_name} Relay 4"
    pin: GPIO15
    icon: mdi:electric-switch

status_led:
  pin:
    number: GPIO13
    inverted: True
