sensor:
  - platform: template
    sensors:
      cover_all:
        friendly_name: "Alle Rollos"
        value_template: >-
          {% if (states('sensor.modbus_sensor_01')|int == 1) and (states('sensor.modbus_sensor_02')|int == 1) and
                (states('sensor.modbus_sensor_03')|int == 1) and (states('sensor.modbus_sensor_04')|int == 1) and
                (states('sensor.modbus_sensor_05')|int == 1) and (states('sensor.modbus_sensor_06')|int == 1) %}
            0
          {% elif (states('sensor.modbus_sensor_01')|int == 1) and (states('sensor.modbus_sensor_02')|int == 1) and
                  (states('sensor.modbus_sensor_03')|int == 1) and (states('sensor.modbus_sensor_04')|int == 1) and
                  (states('sensor.modbus_sensor_05')|int == 1) and (states('sensor.modbus_sensor_06')|int == 1) %}
            100
          {% else %}
            50
          {% endif %}
      cover_rain:
        friendly_name: "Rollos bei Regen"
        value_template: >-
          {% if (states('sensor.modbus_sensor_01')|int == 1) and (states('sensor.modbus_sensor_02')|int == 1) and
                (states('sensor.modbus_sensor_03')|int == 1) and (states('sensor.modbus_sensor_04')|int == 1) %}
            0
          {% elif (states('sensor.modbus_sensor_01')|int == 1) and (states('sensor.modbus_sensor_02')|int == 1) and
                  (states('sensor.modbus_sensor_03')|int == 1) and (states('sensor.modbus_sensor_04')|int == 1) %}
            100
          {% else %}
            50
          {% endif %}

cover:
  - platform: template
    covers:
      kitchen_left_window:
        device_class: shutter
        friendly_name: "Küche links"
        position_template: >-
          {% if states('sensor.modbus_sensor_01')|int == 1 %}
            0
          {% elif states('sensor.modbus_sensor_01')|int == 2 %}
            100
          {% else %}
            50
          {% endif %}
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_kitchen_left_up
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_kitchen_left_down
      kitchen_right_window:
        device_class: shutter
        friendly_name: "Küche rechts"
        position_template: >-
          {% if states('sensor.modbus_sensor_04')|int == 1 %}
            0
          {% elif states('sensor.modbus_sensor_04')|int == 2 %}
            100
          {% else %}
            50
          {% endif %}
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_kitchen_right_up
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_kitchen_right_down
      kitchen_window:
        device_class: shutter
        friendly_name: "Küche Fenster"
        position_template: >-
          {% if (states('sensor.modbus_sensor_01')|int == 1) and (states('sensor.modbus_sensor_04')|int == 1) %}
            0
          {% elif (states('sensor.modbus_sensor_01')|int == 2) and (states('sensor.modbus_sensor_04')|int == 2) %}
            100
          {% else %}
            50
          {% endif %}
        open_cover:
          service: switch.turn_on
          data:
            entity_id:
              - switch.blind_kitchen_left_up
              - switch.blind_kitchen_right_up
        close_cover:
          service: switch.turn_on
          data:
            entity_id:
              - switch.blind_kitchen_left_down
              - switch.blind_kitchen_right_down
      kitchen_door:
        device_class: shutter
        friendly_name: "Küche Balkon"
        position_template: >-
          {% if states('sensor.modbus_sensor_06')|int == 1 %}
            0
          {% elif states('sensor.modbus_sensor_06')|int == 2 %}
            100
          {% else %}
            50
          {% endif %}
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_kitchen_door_up
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_kitchen_door_down
      livingroom_window:
        device_class: shutter
        friendly_name: "Wohnzimmer Fenster"
        position_template: >-
          {% if states('sensor.modbus_sensor_03')|int == 1 %}
            0
          {% elif states('sensor.modbus_sensor_03')|int == 2 %}
            100
          {% else %}
            50
          {% endif %}
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_livingroom_window_up
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_livingroom_window_down
      livingroom_door:
        device_class: shutter
        friendly_name: "Wohnzimmer Balkon"
        position_template: >-
          {% if states('sensor.modbus_sensor_05')|int == 1 %}
            0
          {% elif states('sensor.modbus_sensor_05')|int == 2 %}
            100
          {% else %}
            50
          {% endif %}
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_livingroom_door_up
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_livingroom_door_down
      bedroom_window:
        device_class: shutter
        friendly_name: "Schlafzimmer Fenster"
        position_template: >-
          {% if states('sensor.modbus_sensor_02')|int == 1 %}
            0
          {% elif states('sensor.modbus_sensor_02')|int == 2 %}
            100
          {% else %}
            50
          {% endif %}
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_bedroom_up
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_bedroom_down
      all:
        device_class: shutter
        friendly_name: "Alle Rollos"
        position_template: "{{ states('sensor.cover_all') }}"
        open_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_all_up
        close_cover:
          service: switch.turn_on
          data:
            entity_id: switch.blind_all_down
      rain:
        device_class: shutter
        friendly_name: "Rollos bei Regen"
        position_template: "{{ states('sensor.cover_rain') }}"
        open_cover:
          service: switch.turn_on
          data:
            entity_id:
              - switch.blind_kitchen_left_up
              - switch.blind_kitchen_right_up
              - switch.blind_livingroom_window_up
              - switch.blind_bedroom_up
        close_cover:
          service: switch.turn_on
          data:
            entity_id:
              - switch.blind_kitchen_left_down
              - switch.blind_kitchen_right_down
              - switch.blind_livingroom_window_down
              - switch.blind_bedroom_down

automation:
- id: '1606158583703'
  alias: Covers down on sundown
  description: 'Fährt die Rollos am Abend runter'
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      below: -6.0
  action:
    - service: cover.close_cover
      entity_id: cover.kitchen_window
    - service: cover.close_cover
      entity_id: cover.livingroom_door
    - service: cover.close_cover
      entity_id: cover.bedroom_window
    - service: cover.close_cover
      entity_id: cover.livingroom_window
  mode: single

logbook:
  exclude:
    entities:
      - cover.all
      - cover.kitchen_window
      - cover.rain
      - sensor.cover_all
      - sensor.cover_rain

history:
  exclude:
    entities:
      - automation.covers_down_on_sundown
      - cover.all
      - cover.kitchen_window
      - cover.rain
      - sensor.cover_all
      - sensor.cover_rain
